# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      env:
        NODE_DEBUG: gh-pages
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        npm ci
        npm run deploy -- --repo "https://git:${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" --user "Github Actions Bot <support+actions@github.com>"
